### ISSUE TITLE
readthedocs are missing dependencies

### ISSUE THREAD

**Issue by pmav99** [noaa-ocs-modeling/EnsemblePerturbation#116] opened 2023-11-30 18:27 UTC
E.g. https://ensembleperturbation.readthedocs.io/en/latest/client.html#perturb-tracks

![image](https://github.com/noaa-ocs-modeling/EnsemblePerturbation/assets/411196/711b7a3f-4399-49bb-9386-dbe04a4ada71)

There are more similar errors

**Comment by SorooshMani-NOAA** [comment] 2023-12-01 15:02
This issue seems to be due to `pooch` dependency in `adcircpy`, but `adcircpy` already defines `pooch` as a dependency:
https://github.com/oceanmodeling/adcircpy/blob/main/pyproject.toml

@pmav99 do you have any suggestion as why it's still missing that dependency when generating the documentation?
https://github.com/noaa-ocs-modeling/EnsemblePerturbation/blob/main/.readthedocs.yml

**Comment by pmav99** [comment] 2023-12-01 16:33
Hmm... could it be that the adcircpy version you get on readthedocs is a rather old one? I.e. one before `pooch` became a mandatory deendency of `adcircpy`?

https://github.com/oceanmodeling/adcircpy/commit/5d3c9e941f4dc2f93375040cb483a61e3d74aa6f

**Comment by pmav99** [comment] 2023-12-01 16:34
Your readthedocs builds have been failing for the past 20 months, too: https://readthedocs.org/projects/ensembleperturbation/builds/?page=2

**Comment by SorooshMani-NOAA** [comment] 2023-12-01 16:38
Thanks for your comments. I haven't been paying attention to the readthedocs logs! That's a good place to start for me.

**Comment by SorooshMani-NOAA** [comment] 2023-12-01 17:06
@zacharyburnett is `ensembleperturbation`'s readthedoc project still under your account? I can't seem to add it in my rtd projects because of existing project name.

**Comment by zacharyburnett** [comment] 2023-12-01 17:30
oh yes, it looks like all of these are failing because of missing dependencies in the extras section; @SorooshMani-NOAA I'll add you as a maintainer as well

**Comment by zacharyburnett** [comment] 2023-12-01 17:48
https://github.com/noaa-ocs-modeling/EnsemblePerturbation/pull/117
https://github.com/noaa-ocs-modeling/CoupledModelDriver/pull/161
https://github.com/noaa-ocs-modeling/nemspy/pull/62
https://github.com/oceanmodeling/adcircpy/pull/181

I've made these PRs to add `dunamai` to the docs dependencies (as per the most recent failing build logs), but I'm still not sure why `pooch` is not available at runtime to the ADCIRCpy docs build

**Comment by pmav99** [comment] 2023-12-01 18:01
> It might be that that was the last successful build and thus represents an outdated version of the docs

That's probably the case.

**Comment by SorooshMani-NOAA** [comment] 2023-12-01 18:18
@zacharyburnett thank you, I was the one who should have paid more attention!!

**Comment by SorooshMani-NOAA** [comment] 2023-12-01 20:05
Still after #117 and #119 the issue is **not** fixed:

![Image](https://github.com/noaa-ocs-modeling/EnsemblePerturbation/assets/77082694/7ed5b5a2-ce3e-4f06-8c0f-b913e45d4762)

I need to add UDUNITS2 as well!

**Comment by SorooshMani-NOAA** [comment] 2023-12-02 02:25
Fixed by #121

**Closed by SorooshMani-NOAA** 2023-12-02 02:25 UTC
